---
- hosts: DEB
  remote_user: linest
  gather_facts: false
  tasks:
  - name: Install python3 on Debian-based systems
    apt:
      name: python3
      state: present
    become: yes

- hosts: RH
  remote_user: linest
  gather_facts: false
  tasks:
  - name: Install python3 on RHEL-based systems
    yum:
      name: python3
      state: present
    become: yes
